name: Update checkers table

on:
  push:
    branches:
      - main
    paths:
      - 'cve_bin_tool/checkers/__init__.py'

permissions:
  contents: read

jobs:
  formatting:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update checkers table
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install .
      - name: Run format_checkers.py
        run: |
          python cve_bin_tool/format_checkers.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7.0.7
        with:
          commit-message: "chore: update checkers table"
          title: "chore: update checkers table"
          branch: chore-update-table
          delete-branch: true
          author: GitHub <noreply@github.com>
