name: Linting

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        tool: ['isort', 'black', 'pyupgrade', 'flake8', 'bandit', 'gitlint', 'mypy', 'interrogate']
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pre-commit
          pre-commit install
      - name: Run ${{ matrix.tool }} using pre-commit
        if: ${{ matrix.tool != 'gitlint' }}
        run: |
          pre-commit run ${{ matrix.tool }} --all-files
      - name: Run gitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: ${{ github.event_name == 'pull_request' && matrix.tool == 'gitlint' }}
        run: |
          python -m pip install --upgrade gitlint
          echo "$TITLE" | gitlint

